# Generated by Django 2.1.5 on 2019-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Temp Models',
            },
        ),
    ]
